/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Skills } from "./Skills";
import { SkillsCountArgs } from "./SkillsCountArgs";
import { SkillsFindManyArgs } from "./SkillsFindManyArgs";
import { SkillsFindUniqueArgs } from "./SkillsFindUniqueArgs";
import { DeleteSkillsArgs } from "./DeleteSkillsArgs";
import { SkillsService } from "../skills.service";
@graphql.Resolver(() => Skills)
export class SkillsResolverBase {
  constructor(protected readonly service: SkillsService) {}

  async _skillsItemsMeta(
    @graphql.Args() args: SkillsCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Skills])
  async skillsItems(
    @graphql.Args() args: SkillsFindManyArgs
  ): Promise<Skills[]> {
    return this.service.skillsItems(args);
  }

  @graphql.Query(() => Skills, { nullable: true })
  async skills(
    @graphql.Args() args: SkillsFindUniqueArgs
  ): Promise<Skills | null> {
    const result = await this.service.skills(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Skills)
  async deleteSkills(
    @graphql.Args() args: DeleteSkillsArgs
  ): Promise<Skills | null> {
    try {
      return await this.service.deleteSkills(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
