/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AboutMe } from "./AboutMe";
import { AboutMeCountArgs } from "./AboutMeCountArgs";
import { AboutMeFindManyArgs } from "./AboutMeFindManyArgs";
import { AboutMeFindUniqueArgs } from "./AboutMeFindUniqueArgs";
import { DeleteAboutMeArgs } from "./DeleteAboutMeArgs";
import { AboutMeService } from "../aboutMe.service";
@graphql.Resolver(() => AboutMe)
export class AboutMeResolverBase {
  constructor(protected readonly service: AboutMeService) {}

  async _aboutMesMeta(
    @graphql.Args() args: AboutMeCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [AboutMe])
  async aboutMes(
    @graphql.Args() args: AboutMeFindManyArgs
  ): Promise<AboutMe[]> {
    return this.service.aboutMes(args);
  }

  @graphql.Query(() => AboutMe, { nullable: true })
  async aboutMe(
    @graphql.Args() args: AboutMeFindUniqueArgs
  ): Promise<AboutMe | null> {
    const result = await this.service.aboutMe(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => AboutMe)
  async deleteAboutMe(
    @graphql.Args() args: DeleteAboutMeArgs
  ): Promise<AboutMe | null> {
    try {
      return await this.service.deleteAboutMe(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
